version: '3'
services:
  node:
    container_name: node
    image: node:10
    user: node
    command: bash -c "chmod -R 744 ./ && npm install && npm start"
    ports:
    - "3001:3001"
    volumes:
    - ./node_src:/home/node/app
    working_dir: /home/node/app
  mongo:
    container_name: mongo
    image: mongo:4.0-xenial
    ports:
    - "27017:27017"
    volumes:
    - ./data:/data/db
  mongo-admin:
    container_name: mongo_admin
    image: mongo-express:0.49
    ports:
    - "8081:8081"
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    - ME_CONFIG_MONGODB_SERVER=mongo
